apiVersion: gobackup.io/v1alpha1
kind: Storage
metadata:
  name: azure-storage
  namespace: default
spec:
  type: azure
  config:
    azure:
      account: myazurestorageaccount
      container: backups
      tenant_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      client_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      client_secret_ref:
        name: storage-credentials
        key: azure-client-secret
      keep: 30
      timeout: 600
