apiVersion: gobackup.io/v1alpha1
kind: Storage
metadata:
  name: gcs-storage
  namespace: default
spec:
  type: gcs
  config:
    gcs:
      bucket: my-gcs-bucket
      path: backups/myapp
      credentials_ref:
        name: storage-credentials
        key: gcs-credentials
      keep: 30
      timeout: 600
