version: 2

project_name: gobackup-operator

before:
  hooks:
    - go mod download

builds:
  - id: gobackup-operator
    main: ./cmd/main.go
    binary: gobackup-operator
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - id: gobackup-operator-archive
    builds:
      - gobackup-operator
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: checksums.txt

release:
  name_template: "{{ .Tag }}"
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - typo
