apiVersion: gobackup.io/v1alpha1
kind: Backup
metadata:
  name: my-first-backup
  namespace: gobackup-operator-system
spec:
  databaseRefs:
    - name: example-postgresql
  storageRefs:
    - name: s3-direct
      keep: 5
      timeout: 300
  compressWith:
    type: gzip
  # Schedule is omitted for immediate backup trigger
  schedule:
    cron: "*/1 * * * *" # Run every minute for testing