apiVersion: gobackup.io/v1alpha1
kind: Database
metadata:
  name: example-influxdb
  namespace: default
spec:
  type: influxdb
  config:
    influxdb:
      host: influxdb.example.svc.cluster.local
      token_ref:
        name: database-credentials
        key: token
      bucket: mybucket
      org: myorg
