apiVersion: gobackup.io/v1
kind: Database
metadata:
  name: example-influxdb-direct
  namespace: default
spec:
  type: influxdb
  config:
    host: influxdb.example.svc.cluster.local
    token: mytoken
    bucket: mybucket
    org: myorg
