apiVersion: gobackup.io/v1alpha1
kind: Database
metadata:
  name: example-mariadb
  namespace: default
spec:
  type: mariadb
  config:
    mariadb:
      host: mariadb.example.svc.cluster.local
      port: 3306
      database: exampledb
      username_ref:
        name: database-credentials
        key: username
      password_ref:
        name: database-credentials
        key: password
