apiVersion: gobackup.io/v1alpha1
kind: Database
metadata:
  name: example-mongodb
  namespace: default
spec:
  type: mongodb
  config:
    host: mongodb.example.svc.cluster.local
    port: 27017
    database: exampledb
    username_ref:
      name: database-credentials
      key: username
    password_ref:
      name: database-credentials
      key: password
    auth_db: admin
    oplog: true
