apiVersion: gobackup.io/v1alpha1
kind: Database
metadata:
  name: example-mssql
  namespace: default
spec:
  type: mssql
  config:
    host: mssql.example.svc.cluster.local
    port: 1433
    database: exampledb
    username_ref:
      name: database-credentials
      key: username
    password_ref:
      name: database-credentials
      key: password
    trust_server_certificate: true
