apiVersion: gobackup.io/v1alpha1
kind: Database
metadata:
  name: example-mysql
  namespace: default
spec:
  type: mysql
  config:
    mysql:
      host: mysql.example.svc.cluster.local
      port: 3306
      socket: ''
      database: exampledb
      username_ref:
        name: database-credentials
        key: username
      password_ref:
        name: database-credentials
        key: password
      args: --skip-ssl
