apiVersion: gobackup.io/v1alpha1
kind: Database
metadata:
  name: example-postgresql
  namespace: default
spec:
  type: postgresql
  config:
    postgresql:
      host: localhost
      port: 5432
      socket: ''
      database: exampledb
      username_ref:
        name: database-credentials
        key: username
      password_ref:
        name: database-credentials
        key: password
      tables:
      - table1
      - table2
      exclude_tables:
      - table3
      args: --no-owner
