apiVersion: gobackup.io/v1alpha1
kind: Database
metadata:
  name: example-redis
  namespace: default
spec:
  type: redis
  config:
    host: redis.example.svc.cluster.local
    port: 6379
    password_ref:
      name: database-credentials
      key: password
    mode: sync
